seed: 0
project_name: rotaryNlink_cinn

env:
  type: "RotaryNLink"
  link_lengths: [1.0, 0.8, 0.6]
  joint_limits: [[[-1.5707963267948966, -0.7853981633974483], [0.7853981633974483, 1.5707963267948966]], [[-1.5707963267948966, -1.0471975511965976], [1.0471975511965976, 1.5707963267948966]], [[-3.141592653589793, -0.7853981633974483], [0.7853981633974483, 1.5707963267948966]]]
  n_links: 3
  workspace:
    hx_min: -2.0
    hx_max:  2.0
    hy_min: -2.0
    hy_max:  2.0

data:
  n_train: 100000
  n_test: 10000

model:
  # model
  hidden_dim: 512
  num_blocks: 16 # 8 makes params equalized across models
  num_subnet_blocks: 1
  clamp: 0.6
  basexy_norm_type: "canonical"

  # training
  device: "cpu"
  epochs: 210
  lr: 5e-4
  lr_milestones: [70, 140]
  lr_gamma: 0.1
  batch_size: 256
  grad_clip: 10.

  # optional constraint shaping
  lambda_fk: 0
  fk_ori_weight: 0

eval:
  n_samples_per_h: 200
  n_bins_theta: 72
  eps_hist: 1.0e-9
  sampling_temperature: 0

