seed: 0
project_name: rotarylink_cinn

env:
  type: "RotaryLink"
  link_lengths: [0.8, 1.0]
  joint_limits: None
  n_links: 2
  base_pos_eps: 0.3
  base_heading_stddev: 0.2617993878 # np.pi/12
  workspace:
    hx_min: -2.0
    hx_max:  2.0
    hy_min: -2.0
    hy_max:  2.0

data:
  n_train: 20000
  n_test: 2000

model:
  n_blocks: 16
  hidden: 128
  clamp: 2.0
  lr: 0.001
  batch_size: 256
  epochs: 200
  device: cpu
  lambda_fk: 0
  basexy_norm_type: "standardize"

eval:
  n_samples_per_H: 200
  n_bins_theta: 72
  eps_hist: 1.0e-9

# notes: "this is the first run for cINN that added standardization to H (for conditioning) too!"