seed: 0

env:
  type: "RotaryLink"
  link_lengths: [0.8, 1.0]
  joint_limits: None
  n_links: 2
  base_pos_eps: 0.3
  base_heading_stddev: 0.2617993878 # np.pi/12
  workspace:
    hx_min: -2.0
    hx_max:  2.0
    hy_min: -2.0
    hy_max:  2.0

data:
  n_train: 20000
  n_test:  2000

model:
  name: "knn"
  k: 50
  sigma: 0.35
  metric: "euclidean"
  algorithm: "auto"

eval:
  n_samples_per_H: 200
  n_bins_theta: 72
  eps_hist: 1.0e-9
  sampling_temperature: 0
