seed: 0
project_name: rotaryNlink_cvae

env:
  type: "RotaryNLink"
  link_lengths: [1.0, 0.8, 0.6]
  joint_limits: [[[-1.5707963267948966, -0.7853981633974483], [0.7853981633974483, 1.5707963267948966]], [[-1.5707963267948966, -1.0471975511965976], [1.0471975511965976, 1.5707963267948966]], [[-3.141592653589793, -0.7853981633974483], [0.7853981633974483, 1.5707963267948966]]]
  n_links: 3
  workspace:
    hx_min: -2.0
    hx_max:  2.0
    hy_min: -2.0
    hy_max:  2.0

data:
  n_train: 20000 # was 20000
  n_test:  2000

model:
  name: "cvae"
  type: "resMLP"
  z_dim: 8 # was 6
  hidden_dim: 512
  num_enc_blocks: 4
  num_dec_blocks: 16
  # enc_hidden: [128, 128, 128, 128, 128, 128]
  # dec_hidden: [128, 128, 128, 128, 128, 128]
  lr: 0.001
  lambda_fk: 0
  fk_ori_weight: 0
  batch_size: 256
  
  epochs: 300
  beta: 1.0
  device: "cpu" # set "cuda" if available

features:
  basexy_norm_type: "canonical" # only this is supported for RotaryNLinkEnv rn
  add_fourier_feat: false
  fourier_feat_scale: 10
  fourier_mapping_size: 4

eval:
  n_samples_per_h: 200
  n_bins_theta: 72
  eps_hist: 1.0e-9
  sampling_temperature: 0

