seed: 0
project_name: rotarylink_cvae

env:
  type: "RotaryLink"
  link_lengths: [0.8, 1.0]
  joint_limits: None
  n_links: 2
  base_pos_eps: 0.3
  base_heading_stddev: 0.2617993878 # np.pi/12
  workspace:
    hx_min: -2.0
    hx_max:  2.0
    hy_min: -2.0
    hy_max:  2.0

data:
  n_train: 100000 # was 20000
  n_test:  10000

model:
  name: "cvae"
  type: "resMLP"
  z_dim: 6
  hidden_dim: 512
  num_blocks: 5
  # enc_hidden: [128, 128, 128, 128, 128, 128]
  # dec_hidden: [128, 128, 128, 128, 128, 128]
  lr: 0.001
  lambda_fk: 0.5
  batch_size: 256
  epochs: 200
  beta: 1.0
  device: "cpu" # set "cuda" if available

features:
  basexy_norm_type: "standardize"
  add_fourier_feat: false
  fourier_feat_scale: 10
  fourier_mapping_size: 4

eval:
  n_samples_per_H: 200
  n_bins_theta: 72
  eps_hist: 1.0e-9
  sampling_temperature: 0

